# Generated by Django 3.2 on 2021-10-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='category',
            field=models.CharField(max_length=150),
        ),
    ]
